/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { validationType } from "./types";
export { validationType } from "./types";
export namespace Components {
    interface McTest {
        "disabled": boolean;
        "error": string;
        "errorMessage": string;
        "import_export_field": string;
        "label": string;
        "mapper": string;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "save_only": boolean;
        "tab_ndex": number;
        "validate": () => Promise<boolean>;
        "validations": validationType[];
        "value": unknown;
    }
}
declare global {
    interface HTMLMcTestElement extends Components.McTest, HTMLStencilElement {
    }
    var HTMLMcTestElement: {
        prototype: HTMLMcTestElement;
        new (): HTMLMcTestElement;
    };
    interface HTMLElementTagNameMap {
        "mc-test": HTMLMcTestElement;
    }
}
declare namespace LocalJSX {
    interface McTest {
        "disabled"?: boolean;
        "error"?: string;
        "errorMessage"?: string;
        "import_export_field"?: string;
        "label"?: string;
        "mapper"?: string;
        "name": string;
        "placeholder"?: string;
        "required"?: boolean;
        "save_only"?: boolean;
        "tab_ndex"?: number;
        "validations"?: validationType[];
        "value"?: unknown;
    }
    interface IntrinsicElements {
        "mc-test": McTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mc-test": LocalJSX.McTest & JSXBase.HTMLAttributes<HTMLMcTestElement>;
        }
    }
}
