/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { McTest as McTestElement, defineCustomElement as defineMcTest } from "@placid/core/components/mc-test.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type McTestEvents = NonNullable<unknown>;

export const McTest: StencilReactComponent<McTestElement, McTestEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<McTestElement, McTestEvents>({
        tagName: 'mc-test',
        elementClass: McTestElement,
        // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
        react: React,
        events: {} as McTestEvents,
        defineCustomElement: defineMcTest
    })
    : /*@__PURE__*/ createSSRComponent<McTestElement, McTestEvents>({
        tagName: 'mc-test',
        properties: {
            name: 'name',
            import_export_field: 'import_export_field',
            mapper: 'mapper',
            label: 'label',
            placeholder: 'placeholder',
            error: 'error',
            disabled: 'disabled',
            required: 'required',
            save_only: 'save_only',
            tab_ndex: 'tab_ndex',
            errorMessage: 'error-message'
        },
        hydrateModule: import('@placid/core/hydrate')
    });
